//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SampleViewer.rc
//
#define IDB_BITMAP1                     2
#define IDD_ABOUTBOX                    100
#define IDD_INFOVIEW                    101
#define IDD_ENUMVIEW                    102
#define IDD_UINTVIEW                    103
#define IDD_FLOATVIEW                   104
#define IDD_FEATUREVIEW                 105
#define IDD_CMDVIEW                     106
#define IDR_MAINFRAME                   128
#define IDR_SAMPLETYPE                  129
#define IDS_STRING130                   130
#define IDB_BITMAP2                     134
#define IDB_BITMAP3                     135
#define IDI_ICON1                       137
#define IDI_ICON2                       138
#define IDI_ICON3                       139
#define IDB_BITMAP4                     142
#define IDI_ICON4                       143
#define IDB_BITMAP5                     144
#define IDB_BITMAP6                     145
#define IDB_BITMAP7                     146
#define IDB_BITMAP8                     147
#define IDI_ICON5                       148
#define IDB_BITMAP9                     148
#define IDI_ICON6                       149
#define IDB_BITMAP10                    149
#define IDD_IPINPUT                     151
#define IDD_STRINGVIEW                  152
#define IDD_SAVENEXTFRAME               153
#define IDD_EVENTSVIEW                  154
#define IDD_SERIALVIEW                  155
#define IDI_ICON7                       156
#define IDD_SINTVIEW                    156
#define IDC_INFOVIEW_UID                1000
#define IDC_INFOVIEW_PNUM               1001
#define IDC_VALUEVIEW_LABEL             1001
#define IDC_INFOVIEW_SNUM               1002
#define IDC_ENUMVIEW_COMBOBOX           1002
#define IDC_INFOVIEW_PVER               1003
#define IDC_VALUEVIEW_VALIDATE          1003
#define IDC_INFOVIEW_INTY               1004
#define IDC_VALUEVIEW_RELOAD            1004
#define IDC_INFOVIEW_INID               1005
#define IDC_UINTVIEW_SLIDER             1005
#define IDC_UINTVIEW_VALUE              1007
#define IDC_FLOATVIEW_VALUE             1008
#define IDC_FEATUREVIEW_MODE            1010
#define IDC_FEATUREVIEW_VALUE           1011
#define IDC_FEATUREVIEW_ONOFF           1012
#define IDC_CMDVIEW_BUTTON              1012
#define IDC_FEATUREVIEW_FORMAT          1013
#define IDC_FEATUREVIEW_SLIDER          1013
#define IDC_IPADDRESS1                  1014
#define IDC_STRINGVIEW_VALUE            1016
#define IDC_STATUS                      1018
#define IDC_LIST1                       1020
#define IDC_BUTTON1                     1021
#define IDC_BUTTON2                     1022
#define IDC_CHECK1                      1023
#define IDC_BUTTON3                     1023
#define IDC_EDIT1                       1024
#define IDC_COMBO3                      1027
#define IDC_COMBO4                      1028
#define IDC_COMBO5                      1029
#define IDC_COMBO6                      1030
#define IDC_SINTVIEW_VALUE              1031
#define IDC_SINTVIEW_SLIDER             1032
#define ID_TOOLS_SAVENEXTFRAME          32784
#define PV_STRERR_SUCCESS               61216
#define PV_STRERR_DRIVER                61217
#define PV_STRERR_BADPARAM              61218
#define PV_STRERR_BADHANDLE             61219
#define PV_STRERR_BADSEQ                61220
#define PV_STRERR_CANCELLED             61221
#define PV_STRERR_TOOSMALL              61222
#define PV_STRERR_QUEUEFULL             61223
#define PV_STRERR_BANDWIDTH             61224
#define PV_STRERR_RESOURCES             61225
#define PV_STRERR_NOTFOUND              61226
#define PV_STRERR_DENIED                61227
#define PV_STRERR_UNPLUGGED             61228
#define PV_STRERR_CAMERAFAULT           61229
#define PV_STRERR_NOTSUPPORTED          61230
#define PV_STRERR_NOTVALID              61231
#define PV_STRERR_TIMEOUT               61232
#define PV_STRERR_ALREADYOPEN           61233
#define PV_STRERR_OUTOFRANGE            61234
#define PV_STRERR_APIFAULT              61235
#define PV_STRERR_WRONGTYPE             61236
#define PV_STRERR_FORBIDDEN             61237
#define PV_STRERR_NOSUGG                61238
#define PV_STRERR_UNAVAILABLE           61238
#define PV_STRERR_NETFAULT              61239
#define PV_STRERR_INVALIDSETUP          61240
#define ID_STRTIP_INFO                  61241
#define ID_STRTIP_CTRL                  61242
#define ID_STRTIP_HIST                  61243
#define ID_STRTIP_LIVE                  61244
#define ID_MSGBOX_LOST                  61245
#define IDS_PVERR_SUCCESS               61246
#define IDS_PVERR_CAMERAFAULT           61247
#define IDS_PVERR_INTERNALFAULT         61248
#define IDS_PVERR_BADHANDLE             61249
#define IDS_PVERR_BADSEQUENCE           61250
#define IDS_PVERR_BADPARAMETER          61251
#define IDS_PVERR_NOTFOUND              61252
#define IDS_PVERR_ACCESSDENIED          61253
#define IDS_PVERR_UNPLUGGED             61254
#define IDS_PVERR_INVALIDSETUP          61255
#define IDS_PVERR_RESOURCES             61256
#define IDS_PVERR_BANDWIDTH             61257
#define IDS_PVERR_QUEUEFULL             61258
#define IDS_PVERR_CANCELLED             61259
#define IDS_PVERR_TIMEOUT               61260
#define IDS_PVERR_OUTOFRANGE            61261
#define IDS_PVERR_WRONGTYPE             61262
#define IDS_PVERR_FORBIDDEN             61263
#define IDS_PVERR_UNAVAILABLE           61264
#define ID_STRTIP_SEEK                  61265
#define ID_STRTIP_EXPO                  61266
#define ID_STRTIP_EVENTS                61267
#define ID_STRTIP_SERIAL                61268

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
